// <auto-generated />
using System;
using Approvers.King.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Approvers.King.Migrations
{
    [DbContext(typeof(AppService))]
    [Migration("20241130181742_CreateSlot")]
    partial class CreateSlot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Approvers.King.Common.AppState", b =>
                {
                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Type");

                    b.ToTable("AppStates");
                });

            modelBuilder.Entity("Approvers.King.Common.GachaProbability", b =>
                {
                    b.Property<string>("RandomMessageId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Probability")
                        .HasColumnType("REAL");

                    b.HasKey("RandomMessageId");

                    b.ToTable("GachaProbabilities");
                });

            modelBuilder.Entity("Approvers.King.Common.Slot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConditionPermillage")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Slots");
                });

            modelBuilder.Entity("Approvers.King.Common.User", b =>
                {
                    b.Property<ulong>("DiscordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyGachaPurchasePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlySlotProfitPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TodaySlotExecuteCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
