// <auto-generated />
using Approvers.King.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Approvers.King.Migrations
{
    [DbContext(typeof(AppService))]
    [Migration("20241120163038_AddGachaProbability")]
    partial class AddGachaProbability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Approvers.King.Common.GachaProbability", b =>
                {
                    b.Property<string>("RandomMessageId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Probability")
                        .HasColumnType("REAL");

                    b.HasKey("RandomMessageId");

                    b.ToTable("GachaProbabilities");
                });

            modelBuilder.Entity("Approvers.King.Common.User", b =>
                {
                    b.Property<ulong>("DiscordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyPurchase")
                        .HasColumnType("INTEGER");

                    b.HasKey("DiscordID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
